# GitHub Container Registry pull secret
# This allows Kubernetes to pull private images from ghcr.io
---
apiVersion: v1
kind: Secret
metadata:
  name: ghcr-secret
  namespace: ${{ values.namespace }}
type: kubernetes.io/dockerconfigjson
data:
  .dockerconfigjson: eyJhdXRocyI6eyJnaGNyLmlvIjp7InVzZXJuYW1lIjoiZmVsaXBlYXp2IiwicGFzc3dvcmQiOiJnaHBfeDc5U1NOUkZxRWFnYWhJYlBPMEZxNHpZWWJrdGlhMmVDQ2E5IiwiYXV0aCI6IlptVnNhWEJsWVhwMk9tZG9jRjk0TnpsVFUwNVNSbkZGWVdkaGFFbGlVRTh3Um5FMGVsbFpZbXQwYVdFeVpVTkRZVGs9In19fQ==
